### ISSUE TITLE
Pinout of the board.

### ISSUE THREAD

**Issue by WinD52** [nerocide/jhe42b_buzzer_firmware#1]
Dear author! The description of the circuit and the photos of the board lacks a description of the pinout of the board. How to connect the ST link to the board is not obvious.

**Comment by WinD52** [comment]
Determined the pinout with a multimeter. I hope this is the right option so that you can add it to the project.
![20210807_204103](https://user-images.githubusercontent.com/32848699/128609610-dc31b74a-f0d0-4a57-a1cb-39078045d49f.jpg)

**Comment by master0id** [comment]
Yes, the pinout is correct.

**Comment by nerocide** [comment]
Hi,

thank you for the photo, i've added this information in readme ;)
