### ISSUE TITLE
any progress on firmware?)

### ISSUE THREAD

**Issue by master0id** [nerocide/jhe42b_buzzer_firmware#2]
Hi!

tried to read original firmware - with no success ... chip is locked from reading.. 

Searched over internet - and only find this project. Any luck for buliding such firmware?)

**Comment by nerocide** [comment]
Hi,

well this the kind of problem i faced when starting this project, i've just added usefull informatio nabout it in [readme](https://github.com/nerocide/jhe42b_buzzer_firmware#unlock-chip)

Yes firmware developement is working.

**Comment by master0id** [comment]
When to expect release? I can help with flashing/testing if needed)

**Comment by nerocide** [comment]
I just pushed a working release for JHE42B
